### ISSUE TITLE
Wish banner doesn't seem to work

### ISSUE THREAD

**Issue by Taz-Senpai** [fcannizzaro/genshin-deck#2]
![image](https://user-images.githubusercontent.com/121803491/210230537-4e2e45ff-ac69-4c51-bae4-e62999f469a5.png)

**Comment by fcannizzaro** [comment]
Fixed! I'm thinking about rewriting the plugin with some changes / new actions! (and the settings are a bit weird from the last SD update)

**Comment by Taz-Senpai** [comment]
It works now!! Thank you very much, such a good plugin!! :)

**Comment by Zarkoncheg** [comment]
Greetings! I have same problem with with banners right now.
![image](https://user-images.githubusercontent.com/103814128/222394578-6b921d8c-30fc-4501-b6dc-65c10cdeb1b5.png)

**Comment by Taz-Senpai** [comment]
I guess that the dev if this plugin must update by hand the plugin after each banner update, as there is maybe no way to predict the image banner yet.

**Comment by Zarkoncheg** [comment]
In this case it's better just get timer with standart picture , or something like, I guess.
