### ISSUE TITLE
Text displayed incorrectly

### ISSUE THREAD

**Issue by Caustle** [fcannizzaro/genshin-deck#3]
![image](https://user-images.githubusercontent.com/83898942/225310188-4379a03b-9b26-4f86-959a-68e987216015.png)
Latest stream deck update destroyed of ruined look of the icons.

**Comment by fcannizzaro** [comment]
You can move the title position
![image](https://user-images.githubusercontent.com/6225939/230766293-d4515826-c485-442d-9ac5-6c153e1e6bf8.png)
