### ISSUE TITLE
Does not appear to connect to HoYoLab

### ISSUE THREAD

**Issue by GStarSade** [fcannizzaro/genshin-deck#5]
I've followed the guide to the letter, I believe the API key tag on the website has changed a little but I can't appear to get it working. Any advice here?

![image](https://github.com/fcannizzaro/genshin-deck/assets/6419740/49812369-0cba-4023-9874-14c23eed7b19)

![image](https://github.com/fcannizzaro/genshin-deck/assets/6419740/1ab5ace3-94ea-4f31-924d-101eb8ff9a16)

**Comment by Toitoine17** [comment]
Hi ! I have the same problem, I hope it will be arrange

**Comment by fcannizzaro** [comment]
Hello! I'm starting working again to this project soon. Also Honkai Star Rail will be supported. Probably I'll release this plugin on the Elgato Marketplace.

**Comment by Toitoine17** [comment]
Ok ok , super, thanks

**Comment by GStarSade** [comment]
> Hello! I'm starting working again to this project soon. Also Honkai Star Rail will be supported. Probably I'll release this plugin on the Elgato Marketplace.

Excited about it! Thank you!
